import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home({author}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre o sistema
        </h1>

        O sistema foi feito em live para demonstrar os primeiros passo com o framework next.js.

        <hr/>
        Autor: {author}

        <Link href="/busca">Ir para a Busca</Link>   
        <Link href="/sobre">Sobre mim</Link>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/trending');
  const json = await res.json();

  return {
    props: {
      author: 'Matheus'
    }
  };
}